//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AwardMessage1700.proto
// Note: requires additional types generated from: DataObject.proto
namespace com.tsixi.miner.pbm
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSendAwardByQuest")]
  public partial class ReqSendAwardByQuest : global::ProtoBuf.IExtensible
  {
    public ReqSendAwardByQuest() {}
    

    private uint _message_type = (uint)1700;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1700)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1701;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1701)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private uint _QuestUid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"QuestUid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint QuestUid
    {
      get { return _QuestUid; }
      set { _QuestUid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSendAwardByQuest")]
  public partial class ResSendAwardByQuest : global::ProtoBuf.IExtensible
  {
    public ResSendAwardByQuest() {}
    

    private uint _message_type = (uint)1700;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1700)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1702;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1702)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.Result _result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}