//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/base-message.proto
namespace com.tsixi.mars.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClusterMessage")]
  public partial class ClusterMessage : global::ProtoBuf.IExtensible
  {
    public ClusterMessage() {}
    

    private string _targetId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }

    private uint _sourceId = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sourceId", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sourceId
    {
      get { return _sourceId; }
      set { _sourceId = value; }
    }
    private com.tsixi.mars.protobuf.TXMessage _msg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.tsixi.mars.protobuf.TXMessage msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TXMessage")]
  public partial class TXMessage : global::ProtoBuf.IExtensible
  {
    public TXMessage() {}
    
    private uint _message_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private byte[] _data_message;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"data_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data_message
    {
      get { return _data_message; }
      set { _data_message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqPingMessage")]
  public partial class ReqPingMessage : global::ProtoBuf.IExtensible
  {
    public ReqPingMessage() {}
    

    private uint _message_type = (uint)1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }
    private ulong _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResPingMessage")]
  public partial class ResPingMessage : global::ProtoBuf.IExtensible
  {
    public ResPingMessage() {}
    

    private uint _message_type = (uint)1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }
    private uint _ping;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ping", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ping
    {
      get { return _ping; }
      set { _ping = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqServerTime")]
  public partial class ReqServerTime : global::ProtoBuf.IExtensible
  {
    public ReqServerTime() {}
    

    private uint _message_type = (uint)2;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)2)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResServerTime")]
  public partial class ResServerTime : global::ProtoBuf.IExtensible
  {
    public ResServerTime() {}
    

    private uint _message_type = (uint)2;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)2)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }
    private ulong _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}