//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BattleMessage1600.proto
// Note: requires additional types generated from: DataObject.proto
namespace com.tsixi.miner.pbm
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqKill")]
  public partial class ReqKill : global::ProtoBuf.IExtensible
  {
    public ReqKill() {}
    

    private uint _message_type = (uint)1600;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1600)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1601;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1601)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private uint _targetUid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"targetUid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint targetUid
    {
      get { return _targetUid; }
      set { _targetUid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqMining")]
  public partial class ReqMining : global::ProtoBuf.IExtensible
  {
    public ReqMining() {}
    

    private uint _message_type = (uint)1600;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1600)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1602;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1602)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBattleBegin")]
  public partial class ReqBattleBegin : global::ProtoBuf.IExtensible
  {
    public ReqBattleBegin() {}
    

    private uint _message_type = (uint)1600;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1600)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1603;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1603)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBattleEnd")]
  public partial class ReqBattleEnd : global::ProtoBuf.IExtensible
  {
    public ReqBattleEnd() {}
    

    private uint _message_type = (uint)1600;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1600)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1606;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1606)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private uint _killNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"killNum", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint killNum
    {
      get { return _killNum; }
      set { _killNum = value; }
    }
    private uint _score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private uint _gold;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private uint _ranking;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResBattleEnd")]
  public partial class ResBattleEnd : global::ProtoBuf.IExtensible
  {
    public ResBattleEnd() {}
    

    private uint _message_type = (uint)1600;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1600)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1607;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1607)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRevive")]
  public partial class ReqRevive : global::ProtoBuf.IExtensible
  {
    public ReqRevive() {}
    

    private uint _message_type = (uint)1600;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1600)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1604;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1604)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResReviveResult")]
  public partial class ResReviveResult : global::ProtoBuf.IExtensible
  {
    public ResReviveResult() {}
    

    private uint _message_type = (uint)1600;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1600)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1605;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1605)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.Result _result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGameInit")]
  public partial class ResGameInit : global::ProtoBuf.IExtensible
  {
    public ResGameInit() {}
    

    private uint _message_type = (uint)1600;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1600)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1610;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1610)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private int _battleSid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"battleSid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int battleSid
    {
      get { return _battleSid; }
      set { _battleSid = value; }
    }
    private int _battleUid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"battleUid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int battleUid
    {
      get { return _battleUid; }
      set { _battleUid = value; }
    }
    private int _mapSid;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mapSid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mapSid
    {
      get { return _mapSid; }
      set { _mapSid = value; }
    }
    private readonly global::System.Collections.Generic.List<com.tsixi.miner.pbm.RoleShowInfo> _roles = new global::System.Collections.Generic.List<com.tsixi.miner.pbm.RoleShowInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"roles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.tsixi.miner.pbm.RoleShowInfo> roles
    {
      get { return _roles; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGameInitDone")]
  public partial class ReqGameInitDone : global::ProtoBuf.IExtensible
  {
    public ReqGameInitDone() {}
    

    private uint _message_type = (uint)1600;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1600)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1611;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1611)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGameStart")]
  public partial class ResGameStart : global::ProtoBuf.IExtensible
  {
    public ResGameStart() {}
    

    private uint _message_type = (uint)1600;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1600)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1612;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1612)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameInput")]
  public partial class GameInput : global::ProtoBuf.IExtensible
  {
    public GameInput() {}
    

    private long _roleUid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleUid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long roleUid
    {
      get { return _roleUid; }
      set { _roleUid = value; }
    }

    private float _horizontal = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"horizontal", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float horizontal
    {
      get { return _horizontal; }
      set { _horizontal = value; }
    }

    private float _vertical = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"vertical", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float vertical
    {
      get { return _vertical; }
      set { _vertical = value; }
    }
    private com.tsixi.miner.pbm.Operate _opt;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"opt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.Operate opt
    {
      get { return _opt; }
      set { _opt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGameInput")]
  public partial class ReqGameInput : global::ProtoBuf.IExtensible
  {
    public ReqGameInput() {}
    

    private uint _message_type = (uint)1600;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1600)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1613;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1613)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private com.tsixi.miner.pbm.GameInput _input = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"input", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.tsixi.miner.pbm.GameInput input
    {
      get { return _input; }
      set { _input = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGameInputs")]
  public partial class ResGameInputs : global::ProtoBuf.IExtensible
  {
    public ResGameInputs() {}
    

    private uint _message_type = (uint)1600;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1600)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1614;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1614)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private uint _lfs;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lfs", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint lfs
    {
      get { return _lfs; }
      set { _lfs = value; }
    }
    private readonly global::System.Collections.Generic.List<com.tsixi.miner.pbm.GameInput> _input = new global::System.Collections.Generic.List<com.tsixi.miner.pbm.GameInput>();
    [global::ProtoBuf.ProtoMember(4, Name=@"input", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.tsixi.miner.pbm.GameInput> input
    {
      get { return _input; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Operate")]
    public enum Operate
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WALK", Value=1)]
      WALK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STOP", Value=2)]
      STOP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOOT", Value=3)]
      SHOOT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIG", Value=4)]
      DIG = 4
    }
  
}