//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CupMessage1400.proto
// Note: requires additional types generated from: DataObject.proto
namespace com.tsixi.miner.pbm
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBuyCup")]
  public partial class ReqBuyCup : global::ProtoBuf.IExtensible
  {
    public ReqBuyCup() {}
    

    private uint _message_type = (uint)1400;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1400)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1401;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1401)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private uint _sid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResBuyCup")]
  public partial class ResBuyCup : global::ProtoBuf.IExtensible
  {
    public ResBuyCup() {}
    

    private uint _message_type = (uint)1400;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1400)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1402;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1402)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.Result _result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCupInfo")]
  public partial class ReqCupInfo : global::ProtoBuf.IExtensible
  {
    public ReqCupInfo() {}
    

    private uint _message_type = (uint)1400;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1400)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1403;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1403)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResCupInfo")]
  public partial class ResCupInfo : global::ProtoBuf.IExtensible
  {
    public ResCupInfo() {}
    

    private uint _message_type = (uint)1400;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1400)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1404;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1404)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private readonly global::System.Collections.Generic.List<com.tsixi.miner.pbm.CupData> _cups = new global::System.Collections.Generic.List<com.tsixi.miner.pbm.CupData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cups", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.tsixi.miner.pbm.CupData> cups
    {
      get { return _cups; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCurrentCupInfo")]
  public partial class ReqCurrentCupInfo : global::ProtoBuf.IExtensible
  {
    public ReqCurrentCupInfo() {}
    

    private uint _message_type = (uint)1400;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1400)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1405;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1405)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private com.tsixi.miner.pbm.CupData _cupdata = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cupdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.tsixi.miner.pbm.CupData cupdata
    {
      get { return _cupdata; }
      set { _cupdata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResCurrentCupInfo")]
  public partial class ResCurrentCupInfo : global::ProtoBuf.IExtensible
  {
    public ResCurrentCupInfo() {}
    

    private uint _message_type = (uint)1400;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1400)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1406;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1406)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private com.tsixi.miner.pbm.CupData _cupdata = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cupdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.tsixi.miner.pbm.CupData cupdata
    {
      get { return _cupdata; }
      set { _cupdata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CupData")]
  public partial class CupData : global::ProtoBuf.IExtensible
  {
    public CupData() {}
    
    private uint _sid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private bool _equip;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool equip
    {
      get { return _equip; }
      set { _equip = value; }
    }
    private bool _canBuy;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"canBuy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool canBuy
    {
      get { return _canBuy; }
      set { _canBuy = value; }
    }
    private bool _timeout;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"timeout", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool timeout
    {
      get { return _timeout; }
      set { _timeout = value; }
    }
    private uint _levelUp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"levelUp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint levelUp
    {
      get { return _levelUp; }
      set { _levelUp = value; }
    }

    private ulong _uid = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }

    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}