//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DataObject.proto
namespace com.tsixi.miner.pbm
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleShowInfo")]
  public partial class RoleShowInfo : global::ProtoBuf.IExtensible
  {
    public RoleShowInfo() {}
    

    private int _sit = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sit
    {
      get { return _sit; }
      set { _sit = value; }
    }
    private long _roleUid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleUid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long roleUid
    {
      get { return _roleUid; }
      set { _roleUid = value; }
    }
    private string _roleName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Award")]
  public partial class Award : global::ProtoBuf.IExtensible
  {
    public Award() {}
    

    private uint _sid = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private uint _gold;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private uint _diamond;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private uint _cupExp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"cupExp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint cupExp
    {
      get { return _cupExp; }
      set { _cupExp = value; }
    }
    private uint _propSid;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"propSid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint propSid
    {
      get { return _propSid; }
      set { _propSid = value; }
    }
    private uint _time;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private com.tsixi.miner.pbm.AwardType _awardType;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"awardType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.AwardType awardType
    {
      get { return _awardType; }
      set { _awardType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Result")]
    public enum Result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILURE", Value=1)]
      FAILURE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ILLEGAL", Value=2)]
      ILLEGAL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR", Value=3)]
      ERROR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_CREATED", Value=4)]
      ROLE_CREATED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_REPEAT", Value=5)]
      ROLE_REPEAT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INSUFFICIENT_GOLD", Value=6)]
      INSUFFICIENT_GOLD = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INSUFFICIENT_DIAMOND", Value=7)]
      INSUFFICIENT_DIAMOND = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LENGTH_TOO_LONG", Value=8)]
      LENGTH_TOO_LONG = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEED_GET_AWARD", Value=9)]
      NEED_GET_AWARD = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEASON_NOT_OPENED", Value=10)]
      SEASON_NOT_OPENED = 10
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AwardType")]
    public enum AwardType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENCY", Value=0)]
      CURRENCY = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROP", Value=1)]
      PROP = 1
    }
  
}