//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PropMessage1300.proto
// Note: requires additional types generated from: DataObject.proto
namespace com.tsixi.miner.pbm
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqWearInfo")]
  public partial class ReqWearInfo : global::ProtoBuf.IExtensible
  {
    public ReqWearInfo() {}
    

    private uint _message_type = (uint)1300;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1300)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1301;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1301)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResWearInfo")]
  public partial class ResWearInfo : global::ProtoBuf.IExtensible
  {
    public ResWearInfo() {}
    

    private uint _message_type = (uint)1300;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1300)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1302;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1302)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _propSids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"propSids", DataFormat = global::ProtoBuf.DataFormat.FixedSize, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<uint> propSids
    {
      get { return _propSids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqPropList")]
  public partial class ReqPropList : global::ProtoBuf.IExtensible
  {
    public ReqPropList() {}
    

    private uint _message_type = (uint)1300;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1300)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1303;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1303)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.PropType _propType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"propType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.PropType propType
    {
      get { return _propType; }
      set { _propType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResPropList")]
  public partial class ResPropList : global::ProtoBuf.IExtensible
  {
    public ResPropList() {}
    

    private uint _message_type = (uint)1300;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1300)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1304;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1304)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private com.tsixi.miner.pbm.PropType _propType = com.tsixi.miner.pbm.PropType.BAG;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"propType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.tsixi.miner.pbm.PropType.BAG)]
    public com.tsixi.miner.pbm.PropType propType
    {
      get { return _propType; }
      set { _propType = value; }
    }
    private readonly global::System.Collections.Generic.List<com.tsixi.miner.pbm.PropData> _props = new global::System.Collections.Generic.List<com.tsixi.miner.pbm.PropData>();
    [global::ProtoBuf.ProtoMember(4, Name=@"props", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.tsixi.miner.pbm.PropData> props
    {
      get { return _props; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqWearing")]
  public partial class ReqWearing : global::ProtoBuf.IExtensible
  {
    public ReqWearing() {}
    

    private uint _message_type = (uint)1300;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1300)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1305;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1305)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private uint _propUid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"propUid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint propUid
    {
      get { return _propUid; }
      set { _propUid = value; }
    }
    private com.tsixi.miner.pbm.PropType _propType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"propType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.PropType propType
    {
      get { return _propType; }
      set { _propType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResWearing")]
  public partial class ResWearing : global::ProtoBuf.IExtensible
  {
    public ResWearing() {}
    

    private uint _message_type = (uint)1300;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1300)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1308;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1308)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.Result _result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBuyProp")]
  public partial class ReqBuyProp : global::ProtoBuf.IExtensible
  {
    public ReqBuyProp() {}
    

    private uint _message_type = (uint)1300;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1300)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1306;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1306)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.Currency _currency;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"currency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.Currency currency
    {
      get { return _currency; }
      set { _currency = value; }
    }
    private uint _sid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResBuyPropResultMessage")]
  public partial class ResBuyPropResultMessage : global::ProtoBuf.IExtensible
  {
    public ResBuyPropResultMessage() {}
    

    private uint _message_type = (uint)1300;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1300)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1307;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1307)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.Result _modify_result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"modify_result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.Result modify_result
    {
      get { return _modify_result; }
      set { _modify_result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PropData")]
  public partial class PropData : global::ProtoBuf.IExtensible
  {
    public PropData() {}
    
    private uint _propSid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"propSid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint propSid
    {
      get { return _propSid; }
      set { _propSid = value; }
    }
    private bool _equip;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool equip
    {
      get { return _equip; }
      set { _equip = value; }
    }

    private uint _propUid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"propUid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint propUid
    {
      get { return _propUid; }
      set { _propUid = value; }
    }

    private uint _expiryDate = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"expiryDate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint expiryDate
    {
      get { return _expiryDate; }
      set { _expiryDate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PropType")]
    public enum PropType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BAG", Value=1)]
      BAG = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LANTERN", Value=2)]
      LANTERN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_MODEL", Value=3)]
      ROLE_MODEL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEAPON", Value=4)]
      WEAPON = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Currency")]
    public enum Currency
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIAMOND", Value=0)]
      DIAMOND = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD", Value=1)]
      GOLD = 1
    }
  
}