//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PubMessage1000.proto
// Note: requires additional types generated from: DataObject.proto
namespace com.tsixi.miner.pbm
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLoginMessage")]
  public partial class ReqLoginMessage : global::ProtoBuf.IExtensible
  {
    public ReqLoginMessage() {}
    

    private uint _message_type = (uint)1000;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1001;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1001)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private ulong _user_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResLoginResultMessage")]
  public partial class ResLoginResultMessage : global::ProtoBuf.IExtensible
  {
    public ResLoginResultMessage() {}
    

    private uint _message_type = (uint)1000;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1002;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1002)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.Result _login_result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"login_result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.Result login_result
    {
      get { return _login_result; }
      set { _login_result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCreateRoleMessage")]
  public partial class ReqCreateRoleMessage : global::ProtoBuf.IExtensible
  {
    public ReqCreateRoleMessage() {}
    

    private uint _message_type = (uint)1000;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1003;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1003)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private string _role_name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"role_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string role_name
    {
      get { return _role_name; }
      set { _role_name = value; }
    }
    private ulong _user_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResCreateResultMessage")]
  public partial class ResCreateResultMessage : global::ProtoBuf.IExtensible
  {
    public ResCreateResultMessage() {}
    

    private uint _message_type = (uint)1000;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1004;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1004)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.Result _create_result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"create_result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.Result create_result
    {
      get { return _create_result; }
      set { _create_result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResRoleInfoMessage")]
  public partial class ResRoleInfoMessage : global::ProtoBuf.IExtensible
  {
    public ResRoleInfoMessage() {}
    

    private uint _message_type = (uint)1000;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1005;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1005)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private ulong _user_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private ulong _role_uid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"role_uid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong role_uid
    {
      get { return _role_uid; }
      set { _role_uid = value; }
    }
    private string _role_name;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"role_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string role_name
    {
      get { return _role_name; }
      set { _role_name = value; }
    }
    private uint _gold;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private uint _diamond;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private string _country;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"country", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string country
    {
      get { return _country; }
      set { _country = value; }
    }
    private uint _maxScore;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"maxScore", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint maxScore
    {
      get { return _maxScore; }
      set { _maxScore = value; }
    }
    private uint _accumulateKill;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"accumulateKill", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint accumulateKill
    {
      get { return _accumulateKill; }
      set { _accumulateKill = value; }
    }
    private uint _accumulateScore;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"accumulateScore", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint accumulateScore
    {
      get { return _accumulateScore; }
      set { _accumulateScore = value; }
    }
    private uint _rankSid;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"rankSid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint rankSid
    {
      get { return _rankSid; }
      set { _rankSid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqModifyRoleNameMessage")]
  public partial class ReqModifyRoleNameMessage : global::ProtoBuf.IExtensible
  {
    public ReqModifyRoleNameMessage() {}
    

    private uint _message_type = (uint)1000;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1006;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1006)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private string _new_role_name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"new_role_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string new_role_name
    {
      get { return _new_role_name; }
      set { _new_role_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResModifyRoleNameResultMessage")]
  public partial class ResModifyRoleNameResultMessage : global::ProtoBuf.IExtensible
  {
    public ResModifyRoleNameResultMessage() {}
    

    private uint _message_type = (uint)1000;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1007;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1007)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.Result _modify_result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"modify_result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.Result modify_result
    {
      get { return _modify_result; }
      set { _modify_result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCurrency")]
  public partial class ReqCurrency : global::ProtoBuf.IExtensible
  {
    public ReqCurrency() {}
    

    private uint _message_type = (uint)1000;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1008;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1008)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResCurrency")]
  public partial class ResCurrency : global::ProtoBuf.IExtensible
  {
    public ResCurrency() {}
    

    private uint _message_type = (uint)1000;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1009;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1009)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private uint _golds = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"golds", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint golds
    {
      get { return _golds; }
      set { _golds = value; }
    }

    private uint _diamonds = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"diamonds", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint diamonds
    {
      get { return _diamonds; }
      set { _diamonds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRoleInfoMessage")]
  public partial class ReqRoleInfoMessage : global::ProtoBuf.IExtensible
  {
    public ReqRoleInfoMessage() {}
    

    private uint _message_type = (uint)1000;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1000)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1010;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1010)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private ulong _roleUid = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roleUid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong roleUid
    {
      get { return _roleUid; }
      set { _roleUid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}