//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: QuestMessage1500.proto
namespace com.tsixi.miner.pbm
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRoleQuests")]
  public partial class ReqRoleQuests : global::ProtoBuf.IExtensible
  {
    public ReqRoleQuests() {}
    

    private uint _message_type = (uint)1500;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1500)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1501;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1501)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResRoleQuests")]
  public partial class ResRoleQuests : global::ProtoBuf.IExtensible
  {
    public ResRoleQuests() {}
    

    private uint _message_type = (uint)1500;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1500)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1502;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1502)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private readonly global::System.Collections.Generic.List<com.tsixi.miner.pbm.QuestData> _questData = new global::System.Collections.Generic.List<com.tsixi.miner.pbm.QuestData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"questData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.tsixi.miner.pbm.QuestData> questData
    {
      get { return _questData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqQuestTargetInfo")]
  public partial class ReqQuestTargetInfo : global::ProtoBuf.IExtensible
  {
    public ReqQuestTargetInfo() {}
    

    private uint _message_type = (uint)1500;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1500)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1503;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1503)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private ulong _uid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResQuestTargetInfo")]
  public partial class ResQuestTargetInfo : global::ProtoBuf.IExtensible
  {
    public ResQuestTargetInfo() {}
    

    private uint _message_type = (uint)1500;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1500)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1504;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1504)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private readonly global::System.Collections.Generic.List<com.tsixi.miner.pbm.QuestTargetData> _targetData = new global::System.Collections.Generic.List<com.tsixi.miner.pbm.QuestTargetData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"targetData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.tsixi.miner.pbm.QuestTargetData> targetData
    {
      get { return _targetData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuestData")]
  public partial class QuestData : global::ProtoBuf.IExtensible
  {
    public QuestData() {}
    
    private uint _sid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private bool _finish;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"finish", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool finish
    {
      get { return _finish; }
      set { _finish = value; }
    }
    private ulong _uid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private bool _canGetAward;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"canGetAward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool canGetAward
    {
      get { return _canGetAward; }
      set { _canGetAward = value; }
    }

    private uint _finishTime = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"finishTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint finishTime
    {
      get { return _finishTime; }
      set { _finishTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuestTargetData")]
  public partial class QuestTargetData : global::ProtoBuf.IExtensible
  {
    public QuestTargetData() {}
    
    private uint _sid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private bool _finish;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"finish", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool finish
    {
      get { return _finish; }
      set { _finish = value; }
    }
    private uint _currentValue;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"currentValue", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint currentValue
    {
      get { return _currentValue; }
      set { _currentValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}