//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RoomMessage1900.proto
// Note: requires additional types generated from: DataObject.proto
namespace com.tsixi.miner.pbm
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCreatRoom")]
  public partial class ReqCreatRoom : global::ProtoBuf.IExtensible
  {
    public ReqCreatRoom() {}
    

    private uint _message_type = (uint)1900;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1900)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1901;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1901)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private int _roomSid = (int)1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomSid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int roomSid
    {
      get { return _roomSid; }
      set { _roomSid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResCreatRoomResult")]
  public partial class ResCreatRoomResult : global::ProtoBuf.IExtensible
  {
    public ResCreatRoomResult() {}
    

    private uint _message_type = (uint)1900;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1900)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1902;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1902)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private com.tsixi.miner.pbm.Result _result = com.tsixi.miner.pbm.Result.SUCCESS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.tsixi.miner.pbm.Result.SUCCESS)]
    public com.tsixi.miner.pbm.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqJoinRoom")]
  public partial class ReqJoinRoom : global::ProtoBuf.IExtensible
  {
    public ReqJoinRoom() {}
    

    private uint _message_type = (uint)1900;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1900)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1903;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1903)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResJoinRoomResult")]
  public partial class ResJoinRoomResult : global::ProtoBuf.IExtensible
  {
    public ResJoinRoomResult() {}
    

    private uint _message_type = (uint)1900;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1900)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1904;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1904)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private com.tsixi.miner.pbm.Result _result = com.tsixi.miner.pbm.Result.SUCCESS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.tsixi.miner.pbm.Result.SUCCESS)]
    public com.tsixi.miner.pbm.Result result
    {
      get { return _result; }
      set { _result = value; }
    }

    private com.tsixi.miner.pbm.RoleShowInfo _roleShowInfo = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roleShowInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.tsixi.miner.pbm.RoleShowInfo roleShowInfo
    {
      get { return _roleShowInfo; }
      set { _roleShowInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqQuitRoom")]
  public partial class ReqQuitRoom : global::ProtoBuf.IExtensible
  {
    public ReqQuitRoom() {}
    

    private uint _message_type = (uint)1900;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1900)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1905;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1905)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResQuitRoomResult")]
  public partial class ResQuitRoomResult : global::ProtoBuf.IExtensible
  {
    public ResQuitRoomResult() {}
    

    private uint _message_type = (uint)1900;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1900)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1906;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1906)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private com.tsixi.miner.pbm.Result _result = com.tsixi.miner.pbm.Result.SUCCESS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.tsixi.miner.pbm.Result.SUCCESS)]
    public com.tsixi.miner.pbm.Result result
    {
      get { return _result; }
      set { _result = value; }
    }

    private int _sit = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sit
    {
      get { return _sit; }
      set { _sit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResRoomInfo")]
  public partial class ResRoomInfo : global::ProtoBuf.IExtensible
  {
    public ResRoomInfo() {}
    

    private uint _message_type = (uint)1900;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1900)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1907;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1907)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private int _roomSid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomSid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomSid
    {
      get { return _roomSid; }
      set { _roomSid = value; }
    }
    private int _roomUid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"roomUid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomUid
    {
      get { return _roomUid; }
      set { _roomUid = value; }
    }
    private readonly global::System.Collections.Generic.List<com.tsixi.miner.pbm.RoleShowInfo> _roles = new global::System.Collections.Generic.List<com.tsixi.miner.pbm.RoleShowInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"roles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.tsixi.miner.pbm.RoleShowInfo> roles
    {
      get { return _roles; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBeginMatch")]
  public partial class ReqBeginMatch : global::ProtoBuf.IExtensible
  {
    public ReqBeginMatch() {}
    

    private uint _message_type = (uint)1900;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1900)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1908;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1908)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private uint _roomSid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomSid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roomSid
    {
      get { return _roomSid; }
      set { _roomSid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResBeginMatchResult")]
  public partial class ResBeginMatchResult : global::ProtoBuf.IExtensible
  {
    public ResBeginMatchResult() {}
    

    private uint _message_type = (uint)1900;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1900)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1909;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1909)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private com.tsixi.miner.pbm.Result _result = com.tsixi.miner.pbm.Result.SUCCESS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.tsixi.miner.pbm.Result.SUCCESS)]
    public com.tsixi.miner.pbm.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCancelMatch")]
  public partial class ReqCancelMatch : global::ProtoBuf.IExtensible
  {
    public ReqCancelMatch() {}
    

    private uint _message_type = (uint)1900;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1900)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1910;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1910)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResCancelMatchResult")]
  public partial class ResCancelMatchResult : global::ProtoBuf.IExtensible
  {
    public ResCancelMatchResult() {}
    

    private uint _message_type = (uint)1900;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1900)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1911;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1911)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private com.tsixi.miner.pbm.Result _result = com.tsixi.miner.pbm.Result.SUCCESS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.tsixi.miner.pbm.Result.SUCCESS)]
    public com.tsixi.miner.pbm.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResRoomMatchInfo")]
  public partial class ResRoomMatchInfo : global::ProtoBuf.IExtensible
  {
    public ResRoomMatchInfo() {}
    

    private uint _message_type = (uint)1900;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1900)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1912;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1912)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private ulong _beginTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"beginTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong beginTime
    {
      get { return _beginTime; }
      set { _beginTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}