//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SceneMessage1100.proto
namespace com.tsixi.miner.pbm
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqEnterScene")]
  public partial class ReqEnterScene : global::ProtoBuf.IExtensible
  {
    public ReqEnterScene() {}
    

    private uint _message_type = (uint)1100;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1100)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1101;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1101)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private uint _sceneId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sceneId", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint sceneId
    {
      get { return _sceneId; }
      set { _sceneId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResEnterScene")]
  public partial class ResEnterScene : global::ProtoBuf.IExtensible
  {
    public ResEnterScene() {}
    

    private uint _message_type = (uint)1100;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1100)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1102;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1102)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private uint _sceneId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sceneId", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint sceneId
    {
      get { return _sceneId; }
      set { _sceneId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResQuitScene")]
  public partial class ResQuitScene : global::ProtoBuf.IExtensible
  {
    public ResQuitScene() {}
    

    private uint _message_type = (uint)1100;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1100)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1103;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1103)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private uint _sceneId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sceneId", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint sceneId
    {
      get { return _sceneId; }
      set { _sceneId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}