//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ScoreMessage1200.proto
namespace com.tsixi.miner.pbm
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqUpBattleDataMessage")]
  public partial class ReqUpBattleDataMessage : global::ProtoBuf.IExtensible
  {
    public ReqUpBattleDataMessage() {}
    

    private uint _message_type = (uint)1200;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1200)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1201;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1201)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private uint _ore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ore", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ore
    {
      get { return _ore; }
      set { _ore = value; }
    }
    private uint _killNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"killNum", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint killNum
    {
      get { return _killNum; }
      set { _killNum = value; }
    }
    private uint _score;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private uint _ranking;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private uint _gold;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResUpBattleDataMessage")]
  public partial class ResUpBattleDataMessage : global::ProtoBuf.IExtensible
  {
    public ResUpBattleDataMessage() {}
    

    private uint _message_type = (uint)1200;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1200)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1202;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1202)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.ResUpBattleDataMessage.UpBattleDataResult _up_result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"up_result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.ResUpBattleDataMessage.UpBattleDataResult up_result
    {
      get { return _up_result; }
      set { _up_result = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"UpBattleDataResult")]
    public enum UpBattleDataResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScoreRank")]
  public partial class ScoreRank : global::ProtoBuf.IExtensible
  {
    public ScoreRank() {}
    
    private uint _ranknum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ranknum", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ranknum
    {
      get { return _ranknum; }
      set { _ranknum = value; }
    }
    private ulong _roleUid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleUid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong roleUid
    {
      get { return _roleUid; }
      set { _roleUid = value; }
    }
    private string _roleName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private uint _score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }

    private uint _sid = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqScoreRanklist")]
  public partial class ReqScoreRanklist : global::ProtoBuf.IExtensible
  {
    public ReqScoreRanklist() {}
    

    private uint _message_type = (uint)1200;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1200)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1203;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1203)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.RankType _rankType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.RankType rankType
    {
      get { return _rankType; }
      set { _rankType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResScoreRanklist")]
  public partial class ResScoreRanklist : global::ProtoBuf.IExtensible
  {
    public ResScoreRanklist() {}
    

    private uint _message_type = (uint)1200;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1200)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1204;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1204)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.RankType _rankType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.RankType rankType
    {
      get { return _rankType; }
      set { _rankType = value; }
    }
    private readonly global::System.Collections.Generic.List<com.tsixi.miner.pbm.ScoreRank> _scoreRanklist = new global::System.Collections.Generic.List<com.tsixi.miner.pbm.ScoreRank>();
    [global::ProtoBuf.ProtoMember(4, Name=@"scoreRanklist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.tsixi.miner.pbm.ScoreRank> scoreRanklist
    {
      get { return _scoreRanklist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RankType")]
    public enum RankType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCORE", Value=0)]
      SCORE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KILL", Value=1)]
      KILL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORE", Value=2)]
      ORE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD", Value=3)]
      GOLD = 3
    }
  
}