//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SeasonMessage1800.proto
// Note: requires additional types generated from: DataObject.proto
namespace com.tsixi.miner.pbm
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqJoinSeasonMessage")]
  public partial class ReqJoinSeasonMessage : global::ProtoBuf.IExtensible
  {
    public ReqJoinSeasonMessage() {}
    

    private uint _message_type = (uint)1800;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1800)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1801;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1801)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResJoinSeasonMessage")]
  public partial class ResJoinSeasonMessage : global::ProtoBuf.IExtensible
  {
    public ResJoinSeasonMessage() {}
    

    private uint _message_type = (uint)1800;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1800)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1802;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1802)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.Result _result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSeasonRank")]
  public partial class ReqSeasonRank : global::ProtoBuf.IExtensible
  {
    public ReqSeasonRank() {}
    

    private uint _message_type = (uint)1800;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1800)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1803;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1803)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSeasonRank")]
  public partial class ResSeasonRank : global::ProtoBuf.IExtensible
  {
    public ResSeasonRank() {}
    

    private uint _message_type = (uint)1800;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1800)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1804;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1804)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private readonly global::System.Collections.Generic.List<com.tsixi.miner.pbm.RoleInfo> _roleInfo = new global::System.Collections.Generic.List<com.tsixi.miner.pbm.RoleInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"roleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.tsixi.miner.pbm.RoleInfo> roleInfo
    {
      get { return _roleInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSeasonInfo")]
  public partial class ReqSeasonInfo : global::ProtoBuf.IExtensible
  {
    public ReqSeasonInfo() {}
    

    private uint _message_type = (uint)1800;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1800)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1805;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1805)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSeasonInfo")]
  public partial class ResSeasonInfo : global::ProtoBuf.IExtensible
  {
    public ResSeasonInfo() {}
    

    private uint _message_type = (uint)1800;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1800)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1806;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1806)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private uint _seasonId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"seasonId", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint seasonId
    {
      get { return _seasonId; }
      set { _seasonId = value; }
    }
    private string _beginDate;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"beginDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string beginDate
    {
      get { return _beginDate; }
      set { _beginDate = value; }
    }
    private string _endDate;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"endDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string endDate
    {
      get { return _endDate; }
      set { _endDate = value; }
    }
    private com.tsixi.miner.pbm.SeasonStatus _status;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.SeasonStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private readonly global::System.Collections.Generic.List<com.tsixi.miner.pbm.SeasonAward> _seasonAward = new global::System.Collections.Generic.List<com.tsixi.miner.pbm.SeasonAward>();
    [global::ProtoBuf.ProtoMember(7, Name=@"seasonAward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.tsixi.miner.pbm.SeasonAward> seasonAward
    {
      get { return _seasonAward; }
    }
  
    private uint _joinCount;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"joinCount", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint joinCount
    {
      get { return _joinCount; }
      set { _joinCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRoleInfo")]
  public partial class ReqRoleInfo : global::ProtoBuf.IExtensible
  {
    public ReqRoleInfo() {}
    

    private uint _message_type = (uint)1800;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1800)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1807;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1807)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResRoleInfo")]
  public partial class ResRoleInfo : global::ProtoBuf.IExtensible
  {
    public ResRoleInfo() {}
    

    private uint _message_type = (uint)1800;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1800)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1808;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1808)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.RoleInfo _roleInfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.tsixi.miner.pbm.RoleInfo roleInfo
    {
      get { return _roleInfo; }
      set { _roleInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGetAward")]
  public partial class ReqGetAward : global::ProtoBuf.IExtensible
  {
    public ReqGetAward() {}
    

    private uint _message_type = (uint)1800;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1800)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1809;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1809)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGetAward")]
  public partial class ResGetAward : global::ProtoBuf.IExtensible
  {
    public ResGetAward() {}
    

    private uint _message_type = (uint)1800;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1800)]
    public uint message_type
    {
      get { return _message_type; }
      set { _message_type = value; }
    }

    private uint _cmd = (uint)1810;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)1810)]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private com.tsixi.miner.pbm.Result _result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.tsixi.miner.pbm.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleInfo")]
  public partial class RoleInfo : global::ProtoBuf.IExtensible
  {
    public RoleInfo() {}
    
    private ulong _roleUid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleUid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong roleUid
    {
      get { return _roleUid; }
      set { _roleUid = value; }
    }

    private string _roleName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private uint _score;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }

    private uint _index = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }
    private bool _haveAward;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"haveAward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool haveAward
    {
      get { return _haveAward; }
      set { _haveAward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SeasonAward")]
  public partial class SeasonAward : global::ProtoBuf.IExtensible
  {
    public SeasonAward() {}
    
    private uint _startPercent;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"startPercent", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint startPercent
    {
      get { return _startPercent; }
      set { _startPercent = value; }
    }
    private uint _endPercent;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"endPercent", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint endPercent
    {
      get { return _endPercent; }
      set { _endPercent = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private com.tsixi.miner.pbm.Award _award;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"award", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.tsixi.miner.pbm.Award award
    {
      get { return _award; }
      set { _award = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SeasonStatus")]
    public enum SeasonStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPEN", Value=1)]
      OPEN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLOSE", Value=2)]
      CLOSE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STAND_BY", Value=3)]
      STAND_BY = 3
    }
  
}