//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GameResultEnum.proto
namespace org.alan.chess.proto
{
    [global::ProtoBuf.ProtoContract(Name=@"GameResultEnum")]
    public enum GameResultEnum
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILURE", Value=1)]
      FAILURE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ILLEGAL", Value=2)]
      ILLEGAL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR", Value=3)]
      ERROR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_CREATED", Value=4)]
      ROLE_CREATED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLE_REPEAT", Value=5)]
      ROLE_REPEAT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_GOLD", Value=6)]
      NOT_ENOUGH_GOLD = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_DIAMOND", Value=7)]
      NOT_ENOUGH_DIAMOND = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FINISH_QUEST", Value=8)]
      FINISH_QUEST = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LENGTH_TOO_LONG", Value=9)]
      LENGTH_TOO_LONG = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEED_GET_AWARD", Value=10)]
      NEED_GET_AWARD = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEASON_NOT_OPENED", Value=11)]
      SEASON_NOT_OPENED = 11
    }
  
}