//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GameTips.proto
namespace org.alan.chess.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameTips")]
  public partial class GameTips : global::ProtoBuf.IExtensible
  {
    public GameTips() {}
    

    private int _tipsType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tipsType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tipsType
    {
      get { return _tipsType; }
      set { _tipsType = value; }
    }

    private int _resultCode = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }

    private string _resultDes = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"resultDes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resultDes
    {
      get { return _resultDes; }
      set { _resultDes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}