//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MoveChess.proto
// Note: requires additional types generated from: BattlePoint.proto
namespace org.alan.chess.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveChess")]
  public partial class MoveChess : global::ProtoBuf.IExtensible
  {
    public MoveChess() {}
    

    private org.alan.chess.proto.BattlePoint _fromPoint = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fromPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public org.alan.chess.proto.BattlePoint fromPoint
    {
      get { return _fromPoint; }
      set { _fromPoint = value; }
    }

    private org.alan.chess.proto.BattlePoint _toPoint = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"toPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public org.alan.chess.proto.BattlePoint toPoint
    {
      get { return _toPoint; }
      set { _toPoint = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}