//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RespCancelMatch.proto
// Note: requires additional types generated from: GameResultEnum.proto
namespace org.alan.chess.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespCancelMatch")]
  public partial class RespCancelMatch : global::ProtoBuf.IExtensible
  {
    public RespCancelMatch() {}
    
    private org.alan.chess.proto.GameResultEnum _gameResultEnum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameResultEnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public org.alan.chess.proto.GameResultEnum gameResultEnum
    {
      get { return _gameResultEnum; }
      set { _gameResultEnum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}