//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RespMoveChess.proto
// Note: requires additional types generated from: MoveChess.proto
namespace org.alan.chess.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespMoveChess")]
  public partial class RespMoveChess : global::ProtoBuf.IExtensible
  {
    public RespMoveChess() {}
    

    private long _roleUid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleUid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long roleUid
    {
      get { return _roleUid; }
      set { _roleUid = value; }
    }

    private org.alan.chess.proto.MoveChess _moveChess = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"moveChess", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public org.alan.chess.proto.MoveChess moveChess
    {
      get { return _moveChess; }
      set { _moveChess = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}