//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TeamInfo.proto
// Note: requires additional types generated from: PlayerFighter.proto
namespace org.alan.chess.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeamInfo")]
  public partial class TeamInfo : global::ProtoBuf.IExtensible
  {
    public TeamInfo() {}
    

    private int _teamId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"teamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int teamId
    {
      get { return _teamId; }
      set { _teamId = value; }
    }

    private int _roomId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private readonly global::System.Collections.Generic.List<org.alan.chess.proto.PlayerFighter> _fighters = new global::System.Collections.Generic.List<org.alan.chess.proto.PlayerFighter>();
    [global::ProtoBuf.ProtoMember(3, Name=@"fighters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<org.alan.chess.proto.PlayerFighter> fighters
    {
      get { return _fighters; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}